### Operaciones Aritmeticas:

Pandas permite realizar operaciones aritméticas directamente sobre columnas de un DataFrame. Esto es muy útil para calcular métricas como precios totales, aplicar descuentos, normalizar datos, entre otros.

Estas operaciones se aplican elemento a elemento, es decir, de forma vectorizada, lo cual es muy eficiente.

Operaciones comunes

| Operación               | Símbolo / Método | Ejemplo             |
| ----------------------- | ---------------- | ------------------- |
| Suma                    | `+`              | `df["A"] + df["B"]` |
| Resta                   | `-`              | `df["A"] - df["B"]` |
| Multiplicación          | `*`              | `df["A"] * df["B"]` |
| División                | `/`              | `df["A"] / df["B"]` |
| Potencia                | `**`             | `df["A"] ** 2`      |
| Módulo                  | `%`              | `df["A"] % 3`       |
| Operaciones con escalar | `+`, `*`, etc.   | `df["A"] * 10`      |

| Ejemplo en código                                           | Descripción                                 |
| ----------------------------------------------------------- | ------------------------------------------- |
| `df["Total Revenue"] = df["Units Sold"] * df["Unit Price"]` | Calcula ingreso total por fila.             |
| `df["Unit Price"] * 1.21`                                   | Aplica un 21% de IVA al precio unitario.    |
| `df["Units Sold"] - 1`                                      | Resta una unidad a cada fila.               |
| `df["Unit Price"] / df["Units Sold"]`                       | Calcula precio unitario por unidad vendida. |

Ejemplo 1: Calcular nuevamente la columna Total Revenue (para chequear que esta bien calcualda)

In [1]:
import pandas as pd
# Cargar archivo CSV en un DataFrame
df = pd.read_csv('Online Sales Data.csv')

In [3]:
df.sample(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
14,10015,2024-01-15,Clothing,North Face Down Jacket,2,249.99,499.98,Asia,Debit Card
91,10092,2024-04-01,Home Appliances,Instant Pot Duo Crisp,1,179.99,179.99,Europe,PayPal
27,10028,2024-01-28,Books,Pride and Prejudice by Jane Austen,3,12.99,38.97,North America,Credit Card
92,10093,2024-04-02,Clothing,Adidas Originals Superstar Sneakers,4,79.99,319.96,Asia,Debit Card
120,10121,2024-04-30,Electronics,Apple iPad Air,2,599.99,1199.98,North America,Credit Card
172,10173,2024-06-21,Beauty Products,Paula's Choice Skin Perfecting 2% BHA Liquid E...,1,29.50,29.50,Europe,PayPal
23,10024,2024-01-24,Sports,Adidas FIFA World Cup Football,3,29.99,89.97,Asia,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
114,10115,2024-04-24,Electronics,Amazon Echo Show 10,1,249.99,249.99,North America,Credit Card
47,10048,2024-02-17,Sports,Yeti Rambler Tumbler,6,39.99,239.94,Asia,Credit Card

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    object
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB

In [6]:
df["Total_Revenue_recal"] = round( df["Units Sold"] * df["Unit Price"],2)
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99
...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98

Ejemplo 2 : Verificar su hay diferencias entre la columna Revenue original y la calculada

In [18]:
df["Dif_Revenue"] = df["Total Revenue"] - df["Total_Revenue_recal"]
#mostramos si existen diferencias
df[["Total Revenue", "Total_Revenue_recal","Dif_Revenue",]].sample(10)

     Total Revenue  Total_Revenue_recal  Dif_Revenue
139         139.99               139.99          0.0
16          399.99               399.99          0.0
220          27.00                27.00          0.0
223         459.98               459.98          0.0
107         399.99               399.99          0.0
171          19.98                19.98          0.0
225          80.97                80.97          0.0
236         270.00               270.00          0.0
42         1199.97              1199.97          0.0
130          36.00                36.00          0.0

Ejemplo 3: Crear una nueva columna con el precio con IVA (21%)

In [20]:
df["Precio con IVA"] = round(df["Unit Price"] * 1.21,2)
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89
...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29

Ejemplo 4: Calcular el promedio de ingreso por unidad vendida

In [21]:
df["Ingreso por unidad"] = df["Total Revenue"] / df["Units Sold"]
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99

Ejemplo 4: Aplicar un descuento del 10% al Unit Price y guardar en nueva columna

In [22]:
df["Precio con descuento"] = df["Unit Price"] * 0.90
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991

Ejemplo 5: Añadir una columna que indique cuántas unidades extra se venderían si se suman 2

In [23]:
df["Unidades futuras"] = df["Units Sold"] + 2
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391,6
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991,3
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000,5
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891,5
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500,3
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991,4

### 💾 Guardar tu DataFrame en un archivo que se llame Online_Sales_modificado.csv , lo vamos a necesitar luego

In [24]:
df.to_csv("Online_Sales_modificado.csv", index=False)