### <span style="color:darksalmon;"> En Pandas, podemos eliminar columnas (o filas) usando el método .drop(). </span>

---
###  Eliminación de Columnas:
---

Este método permite remover una o varias columnas especificando su nombre y el eje correspondiente (axis=1 para columnas).

También se puede usar del o asignar None/np.nan si solo se quiere "vaciar" la columna, pero .drop() es el método más limpio y flexible.

```python
df.drop(labels, axis=1, inplace=False)

```

Parámetros clave:

| Parámetro | Uso                                                                          |
| --------- | ---------------------------------------------------------------------------- |
| `labels`  | Nombre de la(s) columna(s) a eliminar                                        |
| `axis`    | `1` para columnas, `0` para filas                                            |
| `inplace` | `True` para modificar el DataFrame original, `False` para devolver una copia |

| Ejemplo                                         | Descripción                                     |
| ----------------------------------------------- | ----------------------------------------------- |
| `df.drop("Region", axis=1)`                     | Elimina la columna "Region"                     |
| `df.drop(["Units Sold", "Unit Price"], axis=1)` | Elimina varias columnas                         |
| `df.drop(columns="Payment Method")`             | Alternativa simplificada para eliminar columnas |
| `del df["ColumnName"]`                          | Elimina directamente, sin usar `.drop()`        |

Ejemplo 1: Eliminar una columna ("Unidades Futuras") del csv que guadaste en el ejercicio anterior

In [1]:
import pandas as pd
# Cargar archivo CSV en un DataFrame
df = pd.read_csv('Online_Sales_modificado.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391,6
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991,3

In [2]:
df_unidades_futuras = df.drop("Unidades futuras", axis=1)
df_unidades_futuras

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991

Ejemplo 2: Eliminar varias columnas a la vez , elimina las columnas Ingreso por unidad y Precio con IVA

In [3]:
df_sin_vars = df.drop(["Ingreso por unidad", "Precio con IVA"], axis=1)
df_sin_vars

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con descuento,Unidades futuras
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,899.991,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,449.991,3
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,62.991,5
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,14.391,6
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,80.991,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,143.991,3
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,81.000,5
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,9.891,5
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,49.500,3
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,26.991,4

Ejemplo 3: Eliminar una columna y modificar el DataFrame original elimina definitivamente en el Dataframe la columna unidades futuras

In [4]:
df.drop("Unidades futuras", axis=1, inplace=True) #trabajamos sobre el df original
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991

Ejemplo 4: Eliminar columnas usando el parámetro columns= , elimina Precio con IVA e Ingreso por unidad

In [5]:
df.drop(columns=["Ingreso por unidad", "Precio con IVA"] , inplace=True)
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,449.991
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,62.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,80.991
...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,143.991
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,81.000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,26.991

Ejemplo 5: Eliminar una columna con del (menos recomendado)

In [6]:
del df["Dif_Revenue"]
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,449.991
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,62.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,80.991
...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,143.991
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,81.000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,26.991

---
### Eliminación de Filas:
---

Pandas tambien permite eliminar filas de un DataFrame utilizando el método .drop( ), especificando el índice o índices de las filas que se desean remover y estableciendo axis=0 (que es el valor por defecto).

También se puede usar lógica booleana para eliminar filas condicionalmente (por ejemplo, con filtros).

```python
df.drop(labels, axis=0, inplace=False)

```

Parámetros clave:

| Forma                                  | Ejemplo                      | Descripción                                  |
| -------------------------------------- | ---------------------------- | -------------------------------------------- |
| Por índice                             | `df.drop(2)`                 | Elimina la fila con índice 2                 |
| Lista de índices                       | `df.drop([0, 3])`            | Elimina múltiples filas                      |
| Condicional (booleano)                 | `df[df["Region"] != "Asia"]` | Mantiene solo filas que cumplen la condición |
| Por nombre si hay índice con etiquetas | `df.drop("fila1", axis=0)`   | Si el índice no es numérico                  |

Ejemplo 1: Eliminar la primera fila por posición

In [8]:
df_sin_fila0 = df.drop(2)
df_sin_fila0

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,449.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,80.991
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card,149.95,26.991
...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,143.991
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,81.000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,26.991

Ejemplo 2: Eliminar varias filas (por ejemplo, posiciones 1 y 4)

In [9]:
df_sin_varias = df.drop([1, 4])
df_sin_varias

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,899.991
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,62.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,14.391
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card,149.95,26.991
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card,2499.99,2249.991
...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,143.991
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,81.000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,26.991

Ejemplo 3: Eliminar todas las transacciones de la región "Asia"

In [10]:
df_sin_asia = df[df["Region"] != "Asia"]  # En realidad no estamos eliminando Mantiene solo las que NO son Asia
df_sin_asia

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,449.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,80.991
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card,2499.99,2249.991
...,...,...,...,...,...,...,...,...,...,...,...
232,10233,2024-08-20,Beauty Products,Fresh Sugar Lip Treatment,1,24.00,24.00,Europe,PayPal,24.00,21.600
234,10235,2024-08-22,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card,299.00,269.100
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,143.991
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,49.500

Ejemplo 4: Eliminar filas por condición compuesta (por ejemplo, Region = Asia y Product Category = Clothing)

In [11]:
condicion = ~((df["Region"] == "Asia") & (df["Product Category"] == "Clothing")) # En realidad no estamos eliminando Mantiene solo las que NO son Asia y no son Clothing
df_filtrado = df[condicion]
df_filtrado

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Precio con descuento
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,899.991
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,449.991
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,14.391
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,80.991
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card,149.95,26.991
...,...,...,...,...,...,...,...,...,...,...,...
234,10235,2024-08-22,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card,299.00,269.100
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,143.991
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,9.891
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,49.500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,26.991