### <span style="color:darksalmon;"> En Pandas, tambien podemos generar columnas </span>

Crear columnas en Pandas es una de las tareas más frecuentes. Podemos hacerlo de varias maneras, dependiendo de si queremos modificar el DataFrame original o crear una copia. 

Estas columnas pueden generarse a partir de cálculos, condiciones, funciones o valores constantes.

Métodos principales

- Asignación directa:

        Se utiliza para crear columnas directamente con una operación, lista, constante o condición.

- Método .assign( ):

        Crea una copia del DataFrame original con nuevas columnas, sin modificar el original.

- Método .insert( ):

        Inserta una nueva columna en una posición específica del DataFrame.


Cuadro explicativo:

| Método                         | Modifica el original | Devuelve copia | Uso típico                      |
| ------------------------------ | -------------------- | -------------- | ------------------------------- |
| Asignación `df["nueva"] = ...` | ✅                    | ❌              | Rápido y directo                |
| `.assign()`                    | ❌                    | ✅              | Múltiples columnas, más control |
| `.insert()`                    | ✅                    | ❌              | Control total de la posición    |

Ejemplo 1: Asignación directa , Crear una columna Discount con valores aleatorios entre 0% y 20% (como decimales)

In [14]:
import pandas as pd
import numpy as np
# Cargar archivo CSV en un DataFrame
df = pd.read_csv('Online_Sales_modificado.csv')
df.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991,3
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000,5
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891,5
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500,3
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991,4

In [15]:
len(df)

240

In [16]:
df["Discount"] = np.random.randint(0, 21, size=len(df)) / 100
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4,0.16
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3,0.01
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5,0.04
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391,6,0.06
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991,3,0.06

Ejemplo 2: Calcular el descuento aplicado (descuento sobre ingreso total)

In [17]:
df["DescuentoAplicado"] = round(df["Total Revenue"] * df["Discount"],2)
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount,DescuentoAplicado
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4,0.16,320.00
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3,0.01,5.00
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5,0.04,8.40
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391,6,0.06,3.84
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991,3,0.06,5.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991,3,0.05,8.00
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000,5,0.12,32.40
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891,5,0.16,5.28
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500,3,0.19,10.45
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991,4,0.17,10.20

Ejemplo 3: Crear la misma columna con .assign() (sin tocar el original)

In [18]:
df_nuevo = df.assign(DescuentoAplicado_assign = round((df["Units Sold"] * df["Unit Price"] * df["Discount"]),2))
df_nuevo

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount,DescuentoAplicado,DescuentoAplicado_assign
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4,0.16,320.00,320.00
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3,0.01,5.00,5.00
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5,0.04,8.40,8.40
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391,6,0.06,3.84,3.84
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991,3,0.06,5.40,5.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991,3,0.05,8.00,8.00
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000,5,0.12,32.40,32.40
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891,5,0.16,5.28,5.28
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500,3,0.19,10.45,10.45
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991,4,0.17,10.20,10.20

Ejemplo 4: Insertar la nueva columna al inicio con .insert()

In [19]:
descuento = round(df["Units Sold"] * df["Unit Price"] * df["Discount"],2)
df.insert(0, "DescuentoAplicado_insert", descuento)

df

,DescuentoAplicado_insert,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount,DescuentoAplicado
0,320.00,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4,0.16,320.00
1,5.00,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3,0.01,5.00
2,8.40,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5,0.04,8.40
3,3.84,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391,6,0.06,3.84
4,5.40,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991,3,0.06,5.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,8.00,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99,0.0,193.59,159.99,143.991,3,0.05,8.00
236,32.40,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,270.00,0.0,108.90,90.00,81.000,5,0.12,32.40
237,5.28,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97,0.0,13.30,10.99,9.891,5,0.16,5.28
238,10.45,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00,0.0,66.55,55.00,49.500,3,0.19,10.45
239,10.20,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98,0.0,36.29,29.99,26.991,4,0.17,10.20