### <span style="color:darksalmon;"> Groupby( ): </span>

El método groupby( ) en Pandas permite agrupar filas que comparten un valor común en una o más columnas, y aplicar funciones de agregación como sum(), mean(), count(), entre muchas otras.

Sintaxis general:
```Python
df.groupby("columna").función()

#O para aplicar sobre columnas específicas:

df.groupby("columna")[["otra_col"]].función()

# También permite agrupar por múltiples columnas

df.groupby(["col1", "col2"]).función()

```
### Cuadro explicativo

| Elemento                                | Descripción                                                          |
| --------------------------------------- | -------------------------------------------------------------------- |
| `groupby("Region")`                     | Agrupa todas las filas por región                                    |
| `.sum()`                                | Suma todos los valores numéricos por grupo                           |
| `.mean()`                               | Calcula la media por grupo                                           |
| `.count()`                              | Cuenta la cantidad de filas por grupo                                |
| `.agg({"col1": "sum", "col2": "mean"})` | Agrega con diferentes funciones por columna                          |
| `.reset_index()`                        | Restaura el índice después del `groupby()` (útil para visualización) |

In [1]:
import pandas as pd
import numpy as np
# Cargar archivo CSV en un DataFrame
df = pd.read_csv('../4.3_Python_fo_Data_Pandas_Manipulación_del_Dato/Online_Sales_modificado.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.35,15.99,14.391,6
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.89,89.99,80.991,3

### 1. Realiza un pequeño analisis Preliminar

In [2]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction ID        240 non-null    int64
 1   Date                  240 non-null    object
 2   Product Category      240 non-null    object
 3   Product Name          240 non-null    object
 4   Units Sold            240 non-null    int64
 5   Unit Price            240 non-null    float64
 6   Total Revenue         240 non-null    float64
 7   Region                240 non-null    object
 8   Payment Method        240 non-null    object
 9   Total_Revenue_recal   240 non-null    float64
 10  Dif_Revenue           240 non-null    float64
 11  Precio con IVA        240 non-null    float64
 12  Ingreso por unidad    240 non-null    float64
 13  Precio con descuento  240 non-null    float64
 14  Unidades futuras      240 non-null    int64
dtypes: float64(7), int64(3), object(5)
memory usage: 28.3+ KB

In [3]:
df.describe()

,Transaction ID,Units Sold,Unit Price,Total Revenue,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
count,240.00000,240.000000,240.000000,240.000000,240.000000,240.0,240.000000,240.000000,240.000000,240.000000
mean,10120.50000,2.158333,236.395583,335.699375,335.699375,0.0,286.040250,236.395583,212.756025,4.158333
std,69.42622,1.322454,429.446695,485.804469,485.804469,0.0,519.630549,429.446695,386.502025,1.322454
min,10001.00000,1.000000,6.500000,6.500000,6.500000,0.0,7.860000,6.500000,5.850000,3.000000
25%,10060.75000,1.000000,29.500000,62.965000,62.965000,0.0,35.700000,29.500000,26.550000,3.000000
50%,10120.50000,2.000000,89.990000,179.970000,179.970000,0.0,108.890000,89.990000,80.991000,4.000000
75%,10180.25000,3.000000,249.990000,399.225000,399.225000,0.0,302.490000,249.990000,224.991000,5.000000
max,10240.00000,10.000000,3899.990000,3899.990000,3899.990000,0.0,4718.990000,3899.990000,3509.991000,12.000000

In [4]:
df.describe(include="O")

,Date,Product Category,Product Name,Region,Payment Method
count,240,240,240,240,240
unique,240,6,232,3,3
top,2024-01-01,Electronics,Dyson Supersonic Hair Dryer,North America,Credit Card
freq,1,40,2,80,120

### 2. Ejercicio básico agrupando sobre una sola columna y sólo una columna en el método de agregación. Haz uno usando el metodo reset_index() y otro sin para comprobar la diferencia

In [5]:
df.head(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.69,69.99,62.991,5

In [11]:
# Sintaxis basica usando Reset Index
df.groupby("Region")["Total Revenue"].min().sort_values(ascending=True).reset_index()

          Region  Total Revenue
0         Europe           6.50
1  North America          17.98
2           Asia          39.60

In [7]:
# Sintaxis basica
df.groupby("Region")["Total Revenue"].sum().sort_values(ascending=False)

Region
North America    36844.34
Asia             22455.45
Europe           21268.06
Name: Total Revenue, dtype: float64

### 3. Ejercicio con una columna en el group by y ninguna en el método de agregación.

In [14]:
df.groupby("Region").count()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
Region,,,,,,,,,,,,,,
Asia,80,80,80,80,80,80,80,80,80,80,80,80,80,80
Europe,80,80,80,80,80,80,80,80,80,80,80,80,80,80
North America,80,80,80,80,80,80,80,80,80,80,80,80,80,80

### 4 Agrupamos por Product Name. Primero vemos los valores únicos y cuantos hay para recordar unique y value_counts

In [17]:
transf=df["Product Name"].unique()
transf_2=pd.DataFrame(transf)
transf_2

                                                   0
0                                      iPhone 14 Pro
1                                   Dyson V11 Vacuum
2                                   Levi's 501 Jeans
3                                  The Da Vinci Code
4                            Neutrogena Skincare Set
..                                               ...
227  Nespresso Vertuo Next Coffee and Espresso Maker
228                        Nike Air Force 1 Sneakers
229           The Handmaid's Tale by Margaret Atwood
230             Sunday Riley Luna Sleeping Night Oil
231                       Yeti Rambler 20 oz Tumbler

[232 rows x 1 columns]

In [18]:
df["Product Name"].value_counts()

Product Name
Dyson Supersonic Hair Dryer                        2
Garmin Forerunner 945                              2
Keurig K-Elite Coffee Maker                        2
Sony WH-1000XM4 Headphones                         2
Dune by Frank Herbert                              2
                                                  ..
Nespresso Vertuo Next Coffee and Espresso Maker    1
Nike Air Force 1 Sneakers                          1
The Handmaid's Tale by Margaret Atwood             1
Sunday Riley Luna Sleeping Night Oil               1
Yeti Rambler 20 oz Tumbler                         1
Name: count, Length: 232, dtype: int64

#### 5. Agrupamos por Product Category pero varias columnas a la vez en el método de agregación

In [19]:
df.head(2)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.99,999.99,899.991,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.99,499.99,449.991,3

In [23]:
df.groupby("Product Category")[["Units Sold","Unit Price", "Total Revenue"]].mean().round(2)

                  Units Sold  Unit Price  Total Revenue
Product Category
Beauty Products         1.15       61.62          65.55
Books                   2.85       16.15          46.55
Clothing                3.62       67.54         203.22
Electronics             1.65      691.59         874.56
Home Appliances         1.48      320.19         466.15
Sports                  2.20      261.28         358.16

### 6. Agrupamos por varias columnas a la vez

In [26]:
df.groupby(["Region", "Payment Method"])["Total Revenue"].sum()

Region         Payment Method
Asia           Credit Card       14326.52
               Debit Card         8128.93
Europe         PayPal            21268.06
North America  Credit Card       36844.34
Name: Total Revenue, dtype: float64

### 7. Agrupamos por una columna y aplicamos en el metodo de agregacion para una sola columna

In [27]:
df.groupby("Region")["Unit Price"].agg(["min", "max"]).reset_index()

          Region   min      max
0           Asia  9.90  1895.00
1         Europe  6.50  1299.99
2  North America  7.99  3899.99

### 8. Agrupamos por una columna y varias columnas en el metodo de agregación pero cambiando el metodo de agregacion en cada columna

In [34]:
df.groupby("Product Category").agg({"Units Sold": "mean","Total Revenue": "sum"}).round().reset_index()

  Product Category  Units Sold  Total Revenue
0  Beauty Products         1.0         2622.0
1            Books         3.0         1862.0
2         Clothing         4.0         8129.0
3      Electronics         2.0        34982.0
4  Home Appliances         1.0        18646.0
5           Sports         2.0        14327.0

### 9 Eneseñamos el método rename para renombrar las columnas que creamos en el group by

In [35]:
df.groupby("Product Category").agg({"Units Sold": "mean","Total Revenue": "sum"}).rename(columns={'Units Sold': 'Cantidad_Media','Total Revenue':'Importe_Total'}).round().reset_index()

  Product Category  Cantidad_Media  Importe_Total
0  Beauty Products             1.0         2622.0
1            Books             3.0         1862.0
2         Clothing             4.0         8129.0
3      Electronics             2.0        34982.0
4  Home Appliances             1.0        18646.0
5           Sports             2.0        14327.0